# Email example using DSPy and crewAI.
# https://medium.com/@Roy.Wong/prompt-optimization-for-ai-agents-dspy-crewai-ollama-in-action-960882663296

import os
import dspy
import crewai
from crewai import Agent, Task, Crew, LLM
from dspy.teleprompt import BootstrapFewShot

lm = dspy.LM(
    model="ollama_chat/llama3:8b",
    api_base="http://localhost:11434",
    api_key=""
)

dspy.configure(lm=lm)

llm = LLM(
    model="ollama_chat/llama3:8b",
    api_base="http://localhost:11434",
    api_key=""
)

# Define Email text block template.
class EmailDraft(dspy.Signature):
    """Generate professional business email."""
    # InputField is supposed to be provided in user query.  OutputField will be generated by LLM.
    intent = dspy.InputField(desc="Purpose of the email")
    email_context = dspy.InputField(desc="Background information")
    tone = dspy.InputField(desc="Tone of the email")
    recipient_context = dspy.InputField(desc="Who the recipient is")

    subject = dspy.OutputField(desc="Email subject")
    body = dspy.OutputField(desc="Full email body")

class EmailWriterModule(dspy.Module):
    def __init__(self):
        super().__init__()
        self.generate = dspy.Predict(EmailDraft)

    def forward(self, intent, email_context, tone, recipient_context):
        return self.generate(
            intent=intent,
            email_context=email_context,
            tone=tone,
            recipient_context=recipient_context
        )

# Provide Email examples.
trainset = [

    dspy.Example(
        intent="Follow up after product demo",
        email_context=(
            "Discussed automation features and integration with Salesforce. "
            "Client expressed concern about timeline and resources."
        ),
        tone="Professional",
        recipient_context="CTO of SaaS startup",
        subject="Following Up on Product Demo",
        body=(
            "Dear John,\n\n"
            "Thank you for taking the time to attend our product demonstration last week. "
            "I appreciated your thoughtful questions about the automation features and Salesforce integration. "
            "Please let me know if you'd like to schedule a follow-up to dive deeper into the implementation plan.\n\n"
            "Best regards,\nAlice"
        )
    ).with_inputs("intent", "email_context", "tone", "recipient_context"),

    dspy.Example(
        intent="Request partnership meeting",
        email_context=(
            "Exploring a reseller partnership in the APAC region with joint marketing opportunities."
        ),
        tone="Formal",
        recipient_context="Director of Strategic Partnerships",
        subject="Request to Discuss Partnership Opportunities",
        body=(
            "Dear Ms. Lee,\n\n"
            "I hope this email finds you well. Our company is exploring the possibility of forming "
            "a reseller partnership in the APAC region. We are particularly interested in discussing "
            "how we might work together on joint marketing initiatives.\n\n"
            "Would you be available for a discussion next week?\n\n"
            "Sincerely,\nAlice"
        )
    ).with_inputs("intent", "email_context", "tone", "recipient_context"),

]

# Define custom evalueation methods.
def email_quality_metric(example, prediction):
    if prediction.subject is None or prediction.body is None:
        return False

    score = 0
    if len(prediction.subject) > 5:
        score += 1
    if len(prediction.body) > 50:
        score += 1
    if "dear" in prediction.body.lower():
        score += 1
    if "regards" in prediction.body.lower() or "sincerely" in prediction.body.lower():
        score += 1
    return score >= 3


# Train LLM with this logic.  You can save this logic in local for later use.
basic_email_module = EmailWriterModule() 
OPTIMIZED_MODULE_FILE = "optimized_email_module.json"

def optimize_email_module():
    teleprompter = BootstrapFewShot(
        metric=email_quality_metric,
        max_bootstrapped_demos=2,
        max_labeled_demos=2,
        max_rounds=1
    )

    print("\n🚀 Optimizing prompt with BootstrapFewShot")

    optimized_module = teleprompter.compile(
        basic_email_module,
        trainset=trainset
    )

    optimized_module.save(OPTIMIZED_MODULE_FILE)

    print("✅ Optimization complete")
    print("💾 Saved optimized module")

    return optimized_module

if os.path.exists(OPTIMIZED_MODULE_FILE):
    print("📦 Loading optimized module")
    optimized_email_module = EmailWriterModule()
    optimized_email_module.load(OPTIMIZED_MODULE_FILE)
else:
    optimized_email_module = optimize_email_module()


def create_patched_llm_call(module):
    def patched_call(self, prompt, **kwargs):
        print("⚡ Using DSPy EmailWriterModule instead of the LLM")

        result = module(
            intent="Follow up after product demo",
            email_context=prompt,
            tone="Professional",
            recipient_context="Business client"
        )
        
        print("📧 Generated Email Subject:", result.subject)
        print("📧 Generated Email Body:", result.body)

        return f"Subject: {result.subject}\n\n{result.body}"
    return patched_call

_original_llm_call = crewai.llm.LLM.call
def apply_monkey_patch(use_optimization=True):
    if use_optimization:
        print("\n🔧 APPLYING DSPy OPTIMIZATION")
        crewai.llm.LLM.call = create_patched_llm_call(optimized_email_module)
    else:
        print("\n⚠️ BASELINE MODE")
        crewai.llm.LLM.call = _original_llm_call

#=============== Finally, run the agent. ==========================

# If set True, it will use the DSPy logic.
apply_monkey_patch(True)

email_agent = Agent(
    role="Email Assistant",
    goal="Write professional business emails",
    backstory="Expert business communication specialist",
    llm = llm,
    verbose=True
)

task = Task(
    description="Write a follow-up email after a product demo discussing Salesforce integration.  The client name is Jason.",
    expected_output="A professional email with subject and body.",
    agent=email_agent
)

crew = Crew(
    agents=[email_agent],
    tasks=[task],
    verbose=True
)

result = crew.kickoff()

print("\nFINAL RESULT\n")
print(result)
